spring:
    application:
        name: deployment-tech
        version: @project.version@
server:
    port: 8080
management:
    endpoints:
        web:
            exposure:
                include: health, prometheus
    metrics:
        tags:
            app-version: @project.version@

