spring:
    application:
        name: deployment-tech
        version: 1.0.1
server:
    port: 8080
management:
    endpoints:
        web:
            exposure:
                include: health, prometheus
    metrics:
        tags:
            app-version: 1.0.1

